### ISSUE TITLE
[Bug] zenpower and BORE modules not available in linuxPackages_cachyos

### ISSUE THREAD

**Issue by fproverbio** [chaotic-cx/nyx#965]
### What happens?

both zenpower (`sudo modprobe zenpower` -> `modprobe: FATAL: Module zenpower not found in directory /run/booted-system/kernel-modules/lib/modules/6.12.9-cachyos`) and BORE (`kernel.sched_bore` -> `sysctl: cannot stat /proc/sys/kernel/sched_bore: No such file or directory`) are not available after installing the cachyOS kernel with `boot.kernelPackages = pkgs.linuxPackages_cachyos;`

### What is expected to happen?

Both zenpower and BORE should be available and loaded at boot?

**Comment by Zerodya** [comment]
I'm also trying to load the zenpower model. Does anyone know how we can import custom modules in the CachyOS kernel? Or do we have to wait for them to be added to the kernel officially?

Zenpower (or zenergy) in particular are really important for Ryzen CPUs because we are not able to read the current power output of the cpu otherwise, which is especially useful in tools like Manohud.

**Comment by PedroHLC** [comment]
I'm closing this issue, BORE is not available in the "flavors" we have ported. It has one of its own that we don't provide:

![Image](https://github.com/user-attachments/assets/4e825168-d1e2-40a3-af0f-7da864ddd046)

---

Zenpower, with all other out-of-tree kernels, was broken (last week) for all CachyOS due to a Nixpkgs bug.  But that was fixed in https://github.com/NixOS/nixpkgs/pull/377327, and imported here at https://github.com/chaotic-cx/nyx/pull/967.

Zenpower currently builds for all our CachyOS kernels except **LTO**. I cannot fix LTO kernel on my own, Nixpkgs does not test their kernel modules built with Clang, they don't offer a Clang kernel to begin with. Trying to handle all those modules would be madness. If anyone wants to try it, fork this repo, and play with `pkgs/linux-cachyos/lib/llvm-module-overlay.nix`.

**Comment by Zerodya** [comment]
Sad to see that zenpower fails to build for the cachyos-lto, since that's what I use [in my config](https://github.com/Zerodya/nix-config/blob/1329a7e00e3e7c1ccd82d9be205978854f310b2a/hosts/desktop/eva01/default.nix#L20), but what about zenergy?

It's still not really clear for me how I would go about adding the module when it's not directly available for a custom kernel like it is for the nixpkgs kernels. Could you please clarify on how I could do that? Would really appreciate it.

**Comment by PedroHLC** [comment]
> like it is for the nixpkgs kernels

It actually is like for Nixpkgs kernels.

When we build a custom kernel in Nix, we end-up with the kernel derivation alone, but Nixpkgs provides `linuxPackagesFor` and that re-builds all known modules with `.override { kernel = linux_your_custom; }`. And voilà, you now have a `linuxPackages_your_custom` attrset with all the realtek drivers, nvidia, zenpower and ZFS inside.

The problem here, is that for LTO, we also change the kernel's stdenv drastically. The modules must re-use this stdenv, and have some extra flags (mostly `LLVM=1`). And that last part is the one that was failing.

To be realist, I didn't try fixing these modules since April 2024, it might be easier now that we have `kernelModuleMakeFlags`. But sadly, I don't have much time between working and maintaining all the other packages.
